//
//  Universities.swift
//  Kolli_UniversityApp
//
//  Created by Kolli,Sai Kumar on 4/18/23.
//

import Foundation

struct Universities {
    var domain = "";
    var list_Array : [UniversityList] = []
    
}


struct UniversityList {
    
    var collegeName=""
    var collegeInfo = ""
    var collegeImage = ""

    
    
}

let dm1 = Universities(domain: "Computer Science",list_Array: [UniversityList(collegeName: "Stanford University",collegeInfo: "Stanford was founded almost 150 years ago on a bedrock of societal purpose. Our mission is to contribute to the world by educating students for lives of leadership and purposeful contribution; advancing fundamental knowledge and cultivating creativity; and accelerating solutions and amplifying their impact.",collegeImage: "stanford"),UniversityList(collegeName: "Northwest Missouri State University",collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum. ",collegeImage: "nwmsu"),
    UniversityList(collegeName: "Harvard University",collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States. ",collegeImage: "harvard"),UniversityList(collegeName: "University of Chicago",collegeInfo: "For more than 125 years, the University of Chicago has forged its own path. This has led to new schools of thought and a transformative education for students, and laid the groundwork for breakthroughs across the sciences, medicine, economics, law, business, history, culture, the arts, and humanistic inquiry.",collegeImage: "chicago"),
        UniversityList(collegeName: "University of California",collegeInfo: "The University of California, Berkeley is a public land-grant research university in Berkeley, California. Established in 1868 as the University of California, it is the state's first land-grant university and the founding campus of the University of California system.",collegeImage: "california")])
let dm2 = Universities(domain: "CyberSecurity",list_Array: [UniversityList(collegeName: "Princeton University",collegeInfo: "Princeton University is a private Ivy League research university in Princeton, New Jersey. Founded in 1746 in Elizabeth as the College of New Jersey, Princeton is the fourth-oldest institution of higher education in the United States and one of the nine colonial colleges chartered before the American Revolution. ",collegeImage: "princeton"),UniversityList(collegeName: "Yale University",collegeInfo: "Yale University is a private Ivy League research university in New Haven, Connecticut. Founded in 1701, Yale is the third-oldest institution of higher education in the United States and one of the nine colonial colleges chartered before the American Revolution. ",collegeImage: "yale"),
    UniversityList(collegeName: "Duke University",collegeInfo: "Duke University is a private research university in Durham, North Carolina. Founded by Methodists and Quakers in the present-day city of Trinity in 1838, the school moved to Durham in 1892.",collegeImage: "duke"),UniversityList(collegeName: "University of Pennsylvania",collegeInfo: "The University of Pennsylvania values diversity and seeks talented students, faculty and staff from diverse backgrounds. The University of Pennsylvania does not discriminate on the basis of race, color, sex, sexual orientation, gender identity, religion, creed, national or ethnic origin, citizenship status, age, disability, veteran status or any other",collegeImage: "pennsylvania"),
        UniversityList(collegeName: "Brown University",collegeInfo: "Brown University is a private Ivy League research university in Providence, Rhode Island. Brown is the seventh-oldest institution of higher education in the United States, founded in 1764 as the College in the English Colony of Rhode Island and Providence Plantations. ",collegeImage: "brown")])
let dm3 = Universities(domain: "Finance",list_Array: [UniversityList(collegeName: "University of Pennsylvania",collegeInfo: "The University of Pennsylvania values diversity and seeks talented students, faculty and staff from diverse backgrounds. The University of Pennsylvania does not discriminate on the basis of race, color, sex, sexual orientation, gender identity, religion, creed, national or ethnic origin, citizenship status, age, disability, veteran status or any other",collegeImage: "pennsylvania"),UniversityList(collegeName: "New York University",collegeInfo: "New York University is a private research university in New York City. Chartered in 1831 by the New York State Legislature, NYU was founded by a group of New Yorkers led by then-Secretary of the Treasury Albert Gallatin.",collegeImage: "newyork"),UniversityList(collegeName: "University of Michigan",collegeInfo: "The mission of the University of Michigan is to serve the people of Michigan and the world through preeminence in creating, communicating, preserving and applying knowledge, art, and academic values, and in developing leaders and citizens who will challenge the present and enrich the future.",collegeImage: "michigan"),UniversityList(collegeName: "University of Virginia",collegeInfo: "The University of Virginia (UVA) is a public research university in Charlottesville, Virginia. It was founded in 1819 by Thomas Jefferson. Set within the Academical Village, a UNESCO World Heritage Site, the university is referred to as a Public Ivy for offering an academic experience similar to that of an Ivy League university.",collegeImage: "virginia"),UniversityList(collegeName: "Ohio State University",collegeInfo: "The Ohio State University, commonly called Ohio State or OSU, is a public land-grant research university in Columbus, Ohio. A member of the University System of Ohio, Ohio State was founded in 1870 as the state's land-grant university and the ninth university in Ohio with the Morrill Act of 1862.",collegeImage: "ohio")])
let dm4 = Universities(domain: "Information Systems",list_Array: [UniversityList(collegeName: "University of Arizona",collegeInfo: "The University of Arizona (Arizona, U of A, UArizona, or UA) is a public land-grant research university in Tucson, Arizona. Founded in 1885 by the 13th Arizona Territorial Legislature, it was the first university in the Arizona Territory.The university is part of the prestigious Association of American Universities (AAU), which represents the 65 leading public and private research universities in North America.",collegeImage: "arizona"),UniversityList(collegeName: "University of Texas Austin",collegeInfo: "The University of Texas at Austin is a public research university in Austin, Texas, and the flagship institution of the University of Texas System. With 40,916 undergraduate students, 11,075 graduate students and 3,133 teaching faculty as of Fall 2021, it is also the largest institution in the system.",collegeImage: "austin"),UniversityList(collegeName: "University of Minnesota",collegeInfo: "The University of Minnesota, formally the University of Minnesota, Twin Cities, is a public land-grant research university in the Twin Cities of Minneapolis and Saint Paul, Minnesota, United States. ",collegeImage: "minnesota"),UniversityList(collegeName: "University of Maryland",collegeInfo: "University of Maryland Global Campus is accredited by the Middle States Commission on Higher Education, 1007 North Orange Street, 4th Floor, MB #166, Wilmington, DE 19801, an institutional accrediting agency recognized by the U.S. Secretary of Education and the Council for Higher Education Accreditation.",collegeImage: "maryland"),UniversityList(collegeName: "Northwest Missouri State University",collegeInfo: "Northwest Missouri State University is a public university in Maryville, Missouri. It has an enrollment of about 8,505 students. Founded in 1905 as a teachers college, its campus is based on the design for Forest Park at the 1904 St. Louis World's Fair and is the official Missouri State Arboretum. ",collegeImage: "nwmsu")])
let dm5 = Universities(domain: "Business Analytics",list_Array: [UniversityList(collegeName: "University of Virginia",collegeInfo: "The University of Virginia (UVA) is a public research university in Charlottesville, Virginia. It was founded in 1819 by Thomas Jefferson. Set within the Academical Village, a UNESCO World Heritage Site, the university is referred to as a Public Ivy for offering an academic experience similar to that of an Ivy League university.",collegeImage: "virginia"),UniversityList(collegeName: "Princeton University",collegeInfo: "Princeton University is a private Ivy League research university in Princeton, New Jersey. Founded in 1746 in Elizabeth as the College of New Jersey, Princeton is the fourth-oldest institution of higher education in the United States and one of the nine colonial colleges chartered before the American Revolution. ",collegeImage: "princeton"),UniversityList(collegeName: "Harvard University",collegeInfo: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Founded in 1636 as Harvard College and named for its first benefactor, the Puritan clergyman John Harvard, it is the oldest institution of higher learning in the United States. ",collegeImage: "harvard"),UniversityList(collegeName: "University of Michigan",collegeInfo: "The mission of the University of Michigan is to serve the people of Michigan and the world through preeminence in creating, communicating, preserving and applying knowledge, art, and academic values, and in developing leaders and citizens who will challenge the present and enrich the future.",collegeImage: "michigan"),UniversityList(collegeName: "Duke University",collegeInfo: "Duke University is a private research university in Durham, North Carolina. Founded by Methodists and Quakers in the present-day city of Trinity in 1838, the school moved to Durham in 1892.",collegeImage: "duke")])

var universities = [dm1,dm2,dm3,dm4,dm5]

